=== alumjoseantoniofornellmarquez/XMLRepo/Libreria/Libreria.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
    <xs:element name="ListaLibros">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="autores" maxOccurs="unbounded" type="xs:string" />
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="autor"  maxOccurs="unbounded" type="xs:string" />
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="ape1" type="xs:string" />
                                                    <xs:element name="ape2" type="xs:string" />
                                                    <xs:element name="nombre" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                    </xs:sequence>
                                </xs:complexType>
                            <xs:element name="titulo" type="xs:string" />
                            <xs:element name="editorial" type="xs:string" />
                            <xs:element name="f.publicacion" type="xs:string" />
                            <xs:element name="ISBN" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alumjoseantoniofornellmarquez/XMLRepo/Libreria/Libreria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Definicion del documento XML-->
<ListaLibros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Libreria.xsd">
    <Libro>
        <autores>
            <autor>
                <ape1>Fornell</ape1>
                <ape2>Marquez</ape2>
                <nombre>Jose Antonio</nombre>
            </autor>
            <autor>
                <ape1>Olid</ape1>
                <ape2>Cordero</ape2>
                <nombre>Sonia</nombre>
            </autor>
        </autores>
        <titulo>Casper y Mia</titulo>
        <editorial>SM</editorial>
        <f.publicacion>2010</f.publicacion>
        <ISBN>788-5557-55-57</ISBN>
    </Libro>
    <Libro>
        <autores>
            <autor>
                <ape1>Perez</ape1>
                <ape2>Rodriguez</ape2>
                <nombre>Pepe</nombre>
            </autor>
        </autores>
        <titulo>Los tres</titulo>
        <editorial>HK</editorial>
        <f.publicacion>1999</f.publicacion>
        <ISBN>44-55-887-447</ISBN>
    </Libro>
    <Libro>
        <autores>
            <autor>
                <ape1>Cordero</ape1>
                <ape2>Perez</ape2>
                <nombre>Mario</nombre>
            </autor>
        </autores>
        <titulo>Chinchon</titulo>
        <editorial>SM</editorial>
        <f.publicacion>2014</f.publicacion>
        <ISBN>62-44-777-487</ISBN>
    </Libro>
    <Libro>
        <autores>
            <autor>
                <ape1>Sanchez</ape1>
                <ape2>Perez</ape2>
                <nombre>Perico</nombre>
            </autor>
        </autores>
        <titulo>Mi moto</titulo>
        <editorial>RG</editorial>
        <f.publicacion>2015</f.publicacion>
        <ISBN>554-342-448</ISBN>
    </Libro>
    <Libro>
        <autores>
            <autor>
                <ape1>Olid</ape1>
                <ape2>Cordero</ape2>
                <nombre>Alejandro</nombre>
            </autor>
        </autores>
        <titulo>Balon</titulo>
        <editorial>RG</editorial>
        <f.publicacion>2011</f.publicacion>
        <ISBN>598-43-44-578</ISBN>
    </Libro>
    <Libro>
        <autores>
            <autor>
                <ape1>Perez</ape1>
                <ape2>Marquez</ape2>
                <nombre>Miguel</nombre>
            </autor>
            <autor>
                <ape1>Matamoros</ape1>
                <ape2>Lopez</ape2>
                <nombre>Juana</nombre>
            </autor>
        </autores>
        <titulo>El Cid</titulo>
        <editorial>SM</editorial>
        <f.publicacion>1999</f.publicacion>
        <ISBN>894-71-71-78</ISBN>
    </Libro>
    <Libro>
        <autores>
            <autor>
                <ape1>Lopez</ape1>
                <ape2>Marquez</ape2>
                <nombre>Monica</nombre>
            </autor>
        </autores>
        <titulo>Ajedrez</titulo>
        <editorial>HK</editorial>
        <f.publicacion>2000</f.publicacion>
        <ISBN>35-44-82-778</ISBN>
    </Libro>
    <Libro>
        <autores>
            <autor>
                <ape1>Fornell</ape1>
                <ape2>Valle</ape2>
                <nombre>Antonio</nombre>
            </autor>
        </autores>
        <titulo>PinkFloyd</titulo>
        <editorial>HK</editorial>
        <f.publicacion>1962</f.publicacion>
        <ISBN>25-55-414-88</ISBN>
    </Libro>
    <Libro>
        <autores>
            <autor>
                <ape1>Lopez</ape1>
                <ape2>Rodriguez</ape2>
                <nombre>Juan</nombre>
            </autor>
        </autores>
        <titulo>Fresas</titulo>
        <editorial>SM</editorial>
        <f.publicacion>2003</f.publicacion>
        <ISBN>65-55-21-90</ISBN>
    </Libro>
    <Libro>
        <autores>
            <autor>
                <ape1>Lopez</ape1>
                <ape2>Rodriguez</ape2>
                <nombre>Alberto</nombre>
            </autor>
        </autores>
        <titulo>Roma</titulo>
        <editorial>HK</editorial>
        <f.publicacion>2012</f.publicacion>
        <ISBN>26-5-91-77</ISBN>
    </Libro>
</ListaLibros>
