=== alumjoseantoniofornellmarquez/XMLRepo/Clientes/clientes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:annotation>
        <xsd:documentation xml:lang="Es-es">
            Esquema para el alta de clientes en sede central
            <fecha>2021-02-10</fecha>
            <autor>Jose Antonio Fornell MÃ¡rquez</autor>
        </xsd:documentation>
    </xsd:annotation>
    <xsd:element name="Clientes" type="clienteDatos" />
    <xsd:complexType name="clienteDatos">
        <xsd:sequence>
            <xsd:element name="Sede" type="sedeDatos" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="sedeDatos">
        <xsd:sequence>
            <xsd:element name="Direccion" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="Empleado" type="xsd:string" />
            <xsd:element name="Fecha" type="xsd:date" />
            <xsd:element name="Descripcion" type="xsd:string" minOccurs="0" />
            <xsd:element name="Cliente" type="clienteDatos" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="codigoSede" type="codigoTipo" use="required" />
    </xsd:complexType>
    <xsd:simpleType name="codigoTipo">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Za-z]([A-Za-z0-9]){7}" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="clienteDatos">
        <xsd:sequence>
            <xsd:element name="Numero_viviendas">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:positiveInteger">
                        <xsd:minInclusive value="1" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="Coste">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:decimal">
                        <xsd:minInclusive value="1" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="Resumen" type="xsd:string" />
            <xsd:element name="Plazo">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:positiveInteger">
                        <xsd:minInclusive value="1" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="codigoCliente" type="tipoCodigoCliente" use="required" />
    </xsd:complexType>
    <xsd:simpleType name="tipoCodigoCliente">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z]{3}-[0-9]{3}" />
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== alumjoseantoniofornellmarquez/XMLRepo/Clientes/clientes_X.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Definicion del documento XML-->
<Clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="clientes.xsd">
    <Sede codigoSede="A1234567">
        <Direccion>Calle de la desesperación</Direccion>
        <Direccion>Calle de la amargura</Direccion>
        <Empleado>Pepe Suarez</Empleado>
        <Fecha>2021-02-03</Fecha>
        <Descripcion>Solvente</Descripcion>
        <Cliente codigoCliente="ABC-123">
            <Numero_viviendas>2</Numero_viviendas>
            <Coste>145.000€</Coste>
            <Resumen>Adosado</Resumen>
            <Plazo>15/09/2021</Plazo>
        </Cliente>
    </Sede>
    <Sede codigoSede="B7654321">
        <Direccion>Calle de la desesperación 2</Direccion>
        <Empleado>Marta Sanchez</Empleado>
        <Fecha>20/02/2021</Fecha>
        <Descripcion>Solvente</Descripcion>
        <Cliente codigoCliente="DEF-456">
            <Numero_viviendas>1</Numero_viviendas>
            <Coste>250.000€</Coste>
            <Resumen>Piso</Resumen>
            <Plazo>25/12/2021</Plazo>
        </Cliente>
    </Sede>
    <Sede codigoSede="C123654">
        <Direccion>Calle de la desesperación 5</Direccion>
        <Empleado>Juan Perez</Empleado>
        <Fecha>20/04/2021</Fecha>
        <Descripcion>Insolvente</Descripcion>
        <Cliente codigoCliente="GHI-789">
            <Numero_viviendas>1</Numero_viviendas>
            <Coste>130.000€</Coste>
            <Resumen>Piso</Resumen>
            <Plazo>15/06/2021</Plazo>
        </Cliente>
    </Sede>
</Clientes>
